//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopxe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<int> loai { get; set; }
        public Nullable<int> hang { get; set; }
        public string imgurl_1 { get; set; }
        public string imgurl_2 { get; set; }
        public string imgurl_3 { get; set; }
        public string imgurl_4 { get; set; }
        public string imgurl_5 { get; set; }
    
        public virtual hang hang1 { get; set; }
        public virtual loai loai1 { get; set; }
    }
}
